export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const GET_GENRES = 'GET_GENRES';
export const FILTER_BY_GENRE = 'FILTER_BY_GENRE'; 
export const FILTER_BY_SOURCE= 'FILTER_BY_SOURCE';
export const SORT_BY = 'SORT_BY';
export const GET_NAME = 'GET_NAME';
export const POST_VIDEOGAME = 'POST_VIDEOGAME';
export const GET_DETAIL = 'GET_DETAIL';
export const SET_LOADING = 'SET_LOADING';
